### PR TITLE
enh: round corners

### PR DESCRIPTION
**Pull request by snitin315**
Refers [open-event-frontend#4306](https://github.com/fossasia/open-event-frontend/issues/4306)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This is incomplete. There are a lot more changes in https://github.com/fossasia/open-event-theme/commit/0206df77b4d535b35a8fd4ddbabdb0f36adb0d12

You have to just change the value in overrides and build the package, not change values in dust manually

**Comment by snitin315** [comment]
https://github.com/fossasia/open-event-theme/blob/5ab0b1399862441fe6d1dd4927600f8d9fef1021/src/themes/default/globals/site.variables#L46

in commit [0206df7](https://github.com/fossasia/open-event-theme/commit/0206df77b4d535b35a8fd4ddbabdb0f36adb0d12) this was changed to ~~4px~~ 0px.

but somehow its 4px again ( maybe changed in latest commit ).

**Comment by iamareebjamal** [comment]
Yes, but the dist was not regenerated

**Comment by snitin315** [comment]
how to generate it?

`gulp build` is throwing error.

**Comment by iamareebjamal** [comment]
Pull latest changes

**Pull request closed without merging**
